### ISSUE TITLE
A veeeery slimmed down mock up idea of some feature requests

### ISSUE THREAD

**Issue by conwaydev** [DarthHater/pgBoardUnchained#9]
![prototype-v2](https://f.cloud.github.com/assets/1868805/1765364/ff8be310-6734-11e3-825d-fb3e41c71d64.jpg)

So I got a little carried away, but:
- A nice feature that I'd like would be more emphasis on the social interaction of profiles, and an awesome tradelist functionality. Heavy importance on messaging and what not would be cool.
- Remove redundancy with navigation items, and provide a search in the main navigation that will search site wide (not mocked up).
- If Feff really wants to sell ads, lets give the option of having big ads. We can create areas throughout the site where we can use the standard common sizes, but maybe we allow for some big guys, give Feff that money. This ad was taken from vice.com.

Again, this is reeeeeeeeally basic, didn't spend very much time on it, but these are some features I think would rule.

**Comment by DarthHater** [comment]
I don't have many issues with it, I think that the big ad is annoying but I think ad's are annoying in general. Back to it won't make much sense if we just lazy load/forever load the threads, maybe that should be back to top on the thread view? Also the front search I think we can do away with and just do a global search now. Seems like it would be a better feature for users.

I'd also like to see how you envision this looking on iPhone 5 and iPad. Mainly interested in mobile since most record traders are broke and own a phone, not a computer.

**Comment by conwaydev** [comment]
I'll make a pretty little mobile mock 4 u
